[package]
name = "winstart"
version = "0.1.1"
authors = ["Allen Wild <allenwild93@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
winapi = { version = "0.3", features = ["shellapi", "winerror"] }
