[package]
name = "winstart"
version = "0.1.0"
authors = ["Allen Wild <allenwild93@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
winapi = { version = "0.3.9", features = ["shellapi"] }
